name: ctc
epochs: 500
warmup_epochs: 2
augment: 3
window: 4
features: wrfeat2
attn_dist_mode: none
delta_cutoff: 1
num_encoder_layers: 6
causal_norm: quiet_softmax
cache: true
cachedir: runs/.cache
d_model: 320
dropout: 0.05
detect_drop: 0.2
pos_embed_per_dim: 32
feat_embed_per_dim: 8
lr: 0.0001
focal_loss_gamma: 0.0
train_samples: 32000
tracking_frequency: 5
tracking_mode: greedy
max_detections: 1024
batch_size: 64
weight_by_dataset: true
detection_folders:
- TRA
input_train:
- data/ctc_2026/2d/BF-C2DL-HSC/01
- data/ctc_2026/2d/BF-C2DL-HSC/02
- data/ctc_2026/2d/BF-C2DL-MuSC/01
- data/ctc_2026/2d/BF-C2DL-MuSC/02
- data/ctc_2026/2d/DIC-C2DH-HeLa/01
# - data/ctc_2026/2d/DIC-C2DH-HeLa/02
- data/ctc_2026/2d/Fluo-C2DL-Huh7/01
- data/ctc_2026/2d/Fluo-C2DL-Huh7/02
- data/ctc_2026/2d/Fluo-C2DL-MSC/01
- data/ctc_2026/2d/Fluo-C2DL-MSC/02
- data/ctc_2026/2d/Fluo-N2DH-GOWT1/01
- data/ctc_2026/2d/Fluo-N2DH-GOWT1/02
- data/ctc_2026/2d/Fluo-N2DH-SIM+/01
- data/ctc_2026/2d/Fluo-N2DH-SIM+/02
- data/ctc_2026/2d/Fluo-N2DL-HeLa/01
# - data/ctc_2026/2d/Fluo-N2DL-HeLa/02
- data/ctc_2026/2d/PhC-C2DH-U373/01
- data/ctc_2026/2d/PhC-C2DH-U373/02
- data/ctc_2026/2d/PhC-C2DL-PSC/01
# - data/ctc_2026/2d/PhC-C2DL-PSC/02
# general_2d datasets (available in data/)
- data/ker_phasecontrast/dataset1/sub_5/exp1_F0002
- data/ker_phasecontrast/dataset1/sub_5/exp1_F0003
- data/ker_phasecontrast/dataset1/sub_5/exp1_F0008
- data/ker_phasecontrast/dataset1/sub_5/exp1_F0014
- data/ker_phasecontrast/dataset2/sub_5/exp1_F0001
- data/ker_phasecontrast/dataset2/sub_5/exp1_F0002
- data/ker_phasecontrast/dataset2/sub_5/exp1_F0004
- data/synthetic_cells_ds2/01
- data/synthetic_cells_ds2/02
- data/synthetic_cells_ds2/03
- data/synthetic_cells_ds2/04
- data/synthetic_cells_ds2/06
- data/synthetic_cells/07
- data/synthetic_cells/08
- data/synthetic_cells/09
- data/synthetic_cells/10
- data/synthetic_cells/11
- data/synthetic_cells/12
- data/synthetic_cells/13
- data/synthetic_cells/14
- data/synthetic_cells/16
- data/synthetic_cells/17
- data/vanvliet_ds2/cib/140408-02
- data/vanvliet_ds2/cib/140408-04
- data/vanvliet_ds2/cib/140408-10
- data/vanvliet/cib/140409-03
- data/vanvliet/cib/140415-08
- data/vanvliet/recA/151027-05
- data/vanvliet/recA/151027-06
- data/vanvliet/recA/151027-10
- data/vanvliet/recA/151028-01
- data/vanvliet/recA/151029-05
- data/vanvliet/recA/151029-11
- data/vanvliet/rpsM/151029_E1-6
- data/vanvliet/rpsM/151101_E2-1
- data/vanvliet/rpsM/151101_E2-2
- data/vanvliet/rpsM/151101_E3-11
- data/vanvliet/rpsM/151101_E4-12
- data/vanvliet_ds2/rpsM/151101_E4-19
- data/vanvliet_ds2/rpsM/151101_E4-20
- data/vanvliet/metA/150317-07
- data/vanvliet/metA/150318-06
- data/vanvliet/metA/150331-12
- data/vanvliet/metA/151222-10
- data/vanvliet/metA/151222-11
- data/vanvliet/pheA/150324-03
- data/vanvliet/pheA/150324-05
- data/vanvliet/pheA/150325-04
- data/vanvliet/pheA/160112-04
- data/vanvliet/trpL/150303-01
- data/vanvliet/trpL/150428-08
- data/vanvliet/trpL/151021-11
- data/deepcell/train/00
- data/deepcell/train/01
- data/deepcell/train/02
- data/deepcell/train/03
- data/deepcell/train/04
- data/deepcell/train/05
- data/deepcell/train/06
- data/deepcell/train/07
- data/deepcell/train/08
- data/deepcell/train/09
- data/deepcell/train/10
- data/deepcell/train/11
- data/deepcell/train/12
- data/deepcell/train/13
- data/deepcell/train/14
- data/deepcell/train/15
- data/deepcell/train/16
- data/deepcell/train/17
- data/deepcell/train/18
- data/deepcell/train/19
- data/deepcell/train/20
- data/deepcell/train/21
- data/deepcell/train/22
- data/deepcell/train/23
- data/deepcell/train/24
- data/deepcell/train/25
- data/deepcell/train/44
- data/deepcell/train/45
- data/deepcell/train_sub2/46
- data/deepcell/train_sub2/47
- data/deepcell/train_sub2/48
- data/deepcell/train_sub2/49
- data/deepcell/train_sub2/50
- data/deepcell/train_sub2/51
- data/deepcell/train_sub2/52
- data/deepcell/train_sub2/53
- data/deepcell/train_sub2/54
- data/deepcell/train_sub2/55
- data/deepcell/train_sub2/56
- data/deepcell/train_sub2/57
- data/deepcell/train_sub2/58
- data/deepcell/train_sub2/59
- data/deepcell/train_sub2/60
- data/deepcell/train_sub2/61
- data/deepcell/train_sub2/62
- data/deepcell/train_sub2/63
- data/deepcell/train_sub2/64
- data/deepcell/train_sub2/65
- data/deepcell/train_sub2/66
- data/deepcell/train_sub2/67
- data/deepcell/train_sub2/68
- data/deepcell/train_sub2/69
- data/deepcell/train_sub2_sliding/70
- data/deepcell/train_sub2_sliding/73
- data/deepcell/train_sub2_sliding/74
- data/deepcell/train_sub2_sliding/75
- data/deepcell/train_sub2_sliding/77
- data/deepcell/train_sub2_sliding/78
- data/deepcell/train_sub2_sliding/79
- data/deepcell/train_sub2_sliding/81
- data/deepcell/train_sub2_sliding/83
- data/trackmate/NMeningitidis/01
- data/trackmate/TCells/01
- data/epithelia/ds2/per01
- data/epithelia/per02
- data/microbial/ds4/00
- data/microbial/ds2/01
- data/microbial/ds1/02
- data/yeast_acdc/MIA_KC_htb1_mCitrine_labeled/Position_2
- data/yeast_acdc/MIA_KC_htb1_mCitrine_labeled/Position_3
- data/yeast_acdc_ds2/MIA_KC_htb1_mCitrine_labeled/Position_4
- data/yeast_acdc_ds2/MIA_KC_htb1_mCitrine_labeled/Position_5
- data/yeast_acdc_ds4/MIA_KC_htb1_mCitrine_flu_control_labeled/Position_1
- data/yeast_acdc/mairhoermann/ds1/Position_16
- data/yeast_acdc/mairhoermann/ds2/Position_35
- data/yeast_acdc/mairhoermann/ds4/Position_41
- data/deepsea/ds2/set_4
- data/deepsea/ds2/set_5
- data/deepsea/ds2/set_7
- data/deepsea/ds1/set_13
- data/deepsea/ds1/set_15
- data/deepsea/ds1/set_17
- data/deepsea/ds1/set_19
- data/deepsea/ds4/set_21
- data/deepsea/ds4/set_25
- data/btrack_ds8/bf/01
- data/btrack_ds16/gfp/01
- data/bacteria_persat/01
- data/bacteria_persat/ds2/03
- data/bacteria_persat/04
- data/mother_machine/train/10
- data/mother_machine/train/21
- data/mother_machine/train/30
- data/mother_machine/train/41
- data/mother_machine/train/50
input_val:
- data/ctc_2026/2d/DIC-C2DH-HeLa/02
- data/ctc_2026/2d/Fluo-N2DL-HeLa/02
- data/ctc_2026/2d/PhC-C2DL-PSC/02
input_test:
- data/ctc_2026/2d/DIC-C2DH-HeLa/02
- data/ctc_2026/2d/Fluo-N2DL-HeLa/02
- data/ctc_2026/2d/PhC-C2DL-PSC/02
