name: vanvliet2
epochs: 500
warmup_epochs: 5
augment: 3
window: 4
attn_dist_mode: v1
delta_cutoff: 1
num_encoder_layers: 6
num_decoder_layers: 6
causal_norm: quiet_softmax
cache: true
cachedir: runs/.cache
compress: true
d_model: 320
dropout: 0.05
pos_embed_per_dim: 32
feat_embed_per_dim: 8
lr: 0.0001
train_samples: 32000
tracking_frequency: 10
tracking_mode: greedy
tracking_max_distance: 128
max_tokens: 2048
batch_size: 192
detection_folders:
- TRA
crop_size:
- 512
- 512
crop_ensure_all_centers: true
attn_positional_bias: rope
features: wrfeat
input_train:
- data/vanvliet2/cib/140409-03  
- data/vanvliet2/cib/140415-08
- data/vanvliet2/recA/151027-05
- data/vanvliet2/recA/151027-06
- data/vanvliet2/recA/151028-01
- data/vanvliet2/recA/151029-05
- data/vanvliet2/recA/151029-11
- data/vanvliet2/rpsM/151029_E1-6
- data/vanvliet2/rpsM/151101_E2-1
- data/vanvliet2/rpsM/151101_E2-2
- data/vanvliet2/rpsM/151101_E3-11
- data/vanvliet2/rpsM/151101_E4-12
- data/vanvliet2/metA/150317-07
- data/vanvliet2/metA/150318-06
- data/vanvliet2/metA/150331-12
- data/vanvliet2/metA/151222-10
- data/vanvliet2/metA/151222-11
- data/vanvliet2/pheA/150324-03
- data/vanvliet2/pheA/150324-05
- data/vanvliet2/pheA/150325-04
- data/vanvliet2/pheA/160112-04
- data/vanvliet2/trpL/150303-01
- data/vanvliet2/trpL/150428-08
- data/vanvliet2/cib/140408-01
- data/vanvliet2/cib/140408-02
- data/vanvliet2/cib/140408-04
- data/vanvliet2/cib/140408-10
- data/vanvliet2/cib/140415-13
- data/vanvliet2/recA/151027-10
- data/vanvliet2/rpsM/151101_E4-19
- data/vanvliet2/rpsM/151101_E4-20
- data/vanvliet2/trpL/150303-08
- data/vanvliet2/cib/140408-09
- data/vanvliet2/cib/140408-11
- data/vanvliet2/metA/150317-03
- data/vanvliet2/metA/150331-11
- data/vanvliet2/metA/150401-02
- data/vanvliet2/metA/151222-05
- data/vanvliet2/pheA/150324-12
- data/vanvliet2/pheA/150325-06
- data/vanvliet2/pheA/150512-14
- data/vanvliet2/pheA/150512-15
- data/vanvliet2/recA/151028-08
- data/vanvliet2/recA/151029-09
- data/vanvliet2/recA/151031-13
- data/vanvliet2/trpL/150310-05
- data/vanvliet2/trpL/150428-06
- data/vanvliet2/trpL/151021-05
- data/vanvliet2/trpL/151021-12

input_val:
- data/vanvliet2/recA/151031-03 
- data/vanvliet2/trpL/151021-11

input_test:
- data/vanvliet2/rpsM/151029_E1-1  
- data/vanvliet2/rpsM/151029_E1-5  
- data/vanvliet2/rpsM/151101_E3-12 
- data/vanvliet2/trpL/150309-04  
- data/vanvliet2/trpL/150310-11  
- data/vanvliet2/pheA/160112-06  
