name: deepcell_sam21_aug
epochs: 1000
warmup_epochs: 5
window: 4
attn_dist_mode: v1
num_encoder_layers: 4
num_decoder_layers: 4
causal_norm: none
d_model: 256
dropout: 0.05
pos_embed_per_dim: 32
lr: 0.0001
train_samples: 32000
max_tokens: 2048
batch_size: 128
detection_folders:
- TRA
crop_size:
- 256
- 256
attn_positional_bias: rope
ndim: 2
# Features config
features: pretrained_feats_aug
#### Additional parameters for pretrained_feats
augment: 3
pretrained_n_augs: 25
pretrained_feats_model: facebook/sam2.1-hiera-base-plus
reduced_pretrained_feat_dim: 128
pretrained_feats_mode: mean_patches_exact
pretrained_feats_additional_props: regionprops_small
rotate_features: true
cachedir: /backup/achard/cache
outdir: /home/achard/trastra_v3_deepcell
# weight_decay: 0.01
#### Logger
logger: wandb
wandb_project: "trackastra_v3_deepcell"
# Paths config

### DEEPCELL SPECIFIC
delta_cutoff: 2
spatial_pos_cutoff: 96
div_upweight: 2
###
cache: true
compress: true
distributed: false
num_workers: 24

input_train:
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/00
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/01
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/02
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/03
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/04
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/05
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/06
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/07
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/08
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/09
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/10
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/11
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/12
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/13
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/14
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/15
# - /backup/achard/CTC_DATA/deepcell/deepcell_full/train/16
- /backup/achard/CTC_DATA/deepcell/deepcell_orig/train/16_corrected
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/17
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/18
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/19
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/20
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/21
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/22
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/23
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/24
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/25
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/26
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/27
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/28
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/29
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/30
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/31
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/32
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/33
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/34
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/35
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/36
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/37
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/38
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/39
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/40
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/41
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/42
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/43
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/44
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/45
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/46
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/47
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/48
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/49
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/50
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/51
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/52
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/53
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/54
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/55
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/56
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/57
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/58
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/59
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/60
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/61
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/62
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/63
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/64
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/65
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/66
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/67
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/68
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/69
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/70
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/71
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/72
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/73
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/74
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/75
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/76
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/77
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/78
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/79
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/80
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/81
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/82
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/83
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/84
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/85
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/86
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/87
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/88
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/89
- /backup/achard/CTC_DATA/deepcell/deepcell_full/train/90
input_val:
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/00
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/01
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/02
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/03
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/04
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/05
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/06
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/07
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/08
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/09
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/10
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/11
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/12
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/13
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/14
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/15
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/16
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/17
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/18
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/19
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/20
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/21
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/22
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/23
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/24
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/25
- /backup/achard/CTC_DATA/deepcell/deepcell_full/val/26

input_test:
- /backup/achard/CTC_DATA/deepcell/deepcell_full/test/00
- /backup/achard/CTC_DATA/deepcell/deepcell_full/test/01
- /backup/achard/CTC_DATA/deepcell/deepcell_full/test/02
- /backup/achard/CTC_DATA/deepcell/deepcell_full/test/03
- /backup/achard/CTC_DATA/deepcell/deepcell_full/test/04
- /backup/achard/CTC_DATA/deepcell/deepcell_full/test/05
- /backup/achard/CTC_DATA/deepcell/deepcell_full/test/06
- /backup/achard/CTC_DATA/deepcell/deepcell_full/test/07
- /backup/achard/CTC_DATA/deepcell/deepcell_full/test/08
- /backup/achard/CTC_DATA/deepcell/deepcell_full/test/09
- /backup/achard/CTC_DATA/deepcell/deepcell_full/test/10
- /backup/achard/CTC_DATA/deepcell/deepcell_full/test/11