# Forked from zih_bacteria.yaml
name: vanvliet_cotracker3_aug
# model: /home/achard/trastra_v2/BEST_2025-06-04_13-23-38_vanvliet_sam21_aug
epochs: 750
warmup_epochs: 5
window: 4
attn_dist_mode: v1
delta_cutoff: 1
num_encoder_layers: 4
num_decoder_layers: 4
causal_norm: none
d_model: 128
dropout: 0.05
pos_embed_per_dim: 32
lr: 0.0001
train_samples: 320005
max_tokens: 2048
batch_size: 64
detection_folders:
- TRA
crop_size:
- 320
- 320
attn_positional_bias: rope
ndim: 2
# Features config
features: pretrained_feats_aug
# features: pretrained_feats
# features: wrfeat
#### Additional parameters for pretrained_feats
augment: 3
pretrained_n_augs: 25
# pretrained_feats_model: facebook/sam2.1-hiera-base-plus
pretrained_feats_model: facebookresearch/co-tracker
# pretrained_feats_model: weigertlab/tarrow
# pretrained_model_path: /home/achard/tarrow_runs/vanvliet_backbone_unet_delta1-2
# pretrained_feats_model: debug/encoded_labels
reduced_pretrained_feat_dim: 128
pretrained_feats_mode: mean_patches_exact
# pretrained_feats_mode: nearest_patch
pretrained_feats_additional_props: regionprops_small
# feat_embed_per_dim: 8 # Reduce additional dimensions added to the features via positional embedding
rotate_features: true
# disable_xy_coords: true
# disable_all_coords: True
cachedir: /home/achard/cache
outdir: /home/achard/trastra_v2
# weight_decay: 0.01
#### Logger
logger: wandb
wandb_project: "trackastra_v2"
# Paths config
cache: true
compress: true
distributed: false
###

input_train:
- /home/achard/CTC_DATA/vanvliet/cib/140409-03  #
- /home/achard/CTC_DATA/vanvliet/cib/140415-08
- /home/achard/CTC_DATA/vanvliet/recA/151027-05
- /home/achard/CTC_DATA/vanvliet/recA/151027-06
# - /home/achard/CTC_DATA/vanvliet/recA/151027-10  # Has an empty frame, annoying
- /home/achard/CTC_DATA/vanvliet/recA/151028-01
- /home/achard/CTC_DATA/vanvliet/recA/151029-05
- /home/achard/CTC_DATA/vanvliet/recA/151029-11
- /home/achard/CTC_DATA/vanvliet/rpsM/151029_E1-6
- /home/achard/CTC_DATA/vanvliet/rpsM/151101_E2-1
- /home/achard/CTC_DATA/vanvliet/rpsM/151101_E2-2
- /home/achard/CTC_DATA/vanvliet/rpsM/151101_E3-11
- /home/achard/CTC_DATA/vanvliet/rpsM/151101_E4-12
- /home/achard/CTC_DATA/vanvliet/metA/150317-07
- /home/achard/CTC_DATA/vanvliet/metA/150318-06
- /home/achard/CTC_DATA/vanvliet/metA/150331-12
- /home/achard/CTC_DATA/vanvliet/metA/151222-10
- /home/achard/CTC_DATA/vanvliet/metA/151222-11
- /home/achard/CTC_DATA/vanvliet/pheA/150324-03
- /home/achard/CTC_DATA/vanvliet/pheA/150324-05
- /home/achard/CTC_DATA/vanvliet/pheA/150325-04
- /home/achard/CTC_DATA/vanvliet/pheA/160112-04
- /home/achard/CTC_DATA/vanvliet/trpL/150303-01
- /home/achard/CTC_DATA/vanvliet/trpL/150303-08

input_val:
- /home/achard/CTC_DATA/vanvliet/trpL/150428-08
- /home/achard/CTC_DATA/vanvliet/trpL/151021-11

input_test:
# - data/CTC_DATA/vanvliet/cib/140408-01  # dense labels not precise
- /home/achard/CTC_DATA/vanvliet/rpsM/151029_E1-1  # ok
- /home/achard/CTC_DATA/vanvliet/rpsM/151029_E1-5  # ok
- /home/achard/CTC_DATA/vanvliet/rpsM/151101_E3-12  # ok
- /home/achard/CTC_DATA/vanvliet/trpL/150309-04  # ok
# - data/CTC_DATA/vanvliet/trpL/150310-05  # was empty
- /home/achard/CTC_DATA/vanvliet/trpL/150310-11  # not in delta test set. quite some global moving!
- /home/achard/CTC_DATA/vanvliet/pheA/160112-06  # ok. tricky. not in delta test set.
