batch_size: 8
crop_size:
- 256
- 256
detection_folders:
- TRA
dropout: 0.0
example_images: False  # Slow
input_train:
- data/ctc_2024/Fluo-N2DL-HeLa/train/02
input_val:
- data/ctc_2024/Fluo-N2DL-HeLa/train/01
max_tokens: 2048
train_samples: 100
name: example
ndim: 2
num_decoder_layers: 5
num_encoder_layers: 5
outdir: runs
distributed: False
window: 6
